### ISSUE TITLE
raisimUnity does not operate.

### ISSUE THREAD

**Issue by alswns314** [jhwangbo/ME491_2022_project#1]
Graphic card: nvidia GeForce RTX 3070 Ti
OS: Linux-x86_64
Nvidia driver version: 510.85.02

raisimUnity does not operate(so does openGL ver.). 
when I double click raisimUnity.x86_64, the window opens for a moment and then disappears.

**Comment by jhwangbo** [comment]
Did you install Vulkan? Try this link

https://linuxconfig.org/install-and-test-vulkan-on-linux

**Comment by alswns314** [comment]
I have already tried to install vulkan  

Vulkan on Ubuntu Linux
NVIDIA

$ sudo apt install nvidia-graphics-drivers-396 nvidia-settings vulkan vulkan-utils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nvidia-graphics-drivers-396
E: Unable to locate package vulkan

this error came out

And I checked the vulkan version

$ /usr/bin/vulkaninfo | head -n 5
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
VULKANINFO
Vulkan Instance Version: 1.2.131
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.

It seems to have vulkan installed by default.

**Comment by jhwangbo** [comment]
``E: Unable to locate package vulkan``
this means that it doesn't know where the package is. Did you run these lines?

  $ sudo add-apt-repository ppa:oibaf/graphics-drivers
  $ sudo apt update
  $ sudo apt upgrade

It is written in the link.

And do not install nvidia-graphics-drivers-396. Install the latest one like ``nvidia-graphics-drivers-515``. Your 510 driver should work fine.

What do you mean by "so does openGL ver"?  Do you mean neither? 

Run both executables in the terminal and copy paste the output.

**Comment by alswns314** [comment]
$ ./raisimUnity.x86_64
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Segmentation fault (core dumped)

**Comment by jhwangbo** [comment]
Please read my previous comments carefully. I asked multiple questions

**Comment by alswns314** [comment]
I'm sorry professor. 

I did run the lines below

$ sudo add-apt-repository ppa:oibaf/graphics-drivers
$ sudo apt update
$ sudo apt upgrade

But, it didn't help to fix my problem

there are RaisimUnity of two versions and neither did not operate.

**Comment by TexnoMann** [comment]
Did you use docker? https://github.com/leggedrobotics/raisimGym/issues/4

**Comment by jhwangbo** [comment]
You have to run this locally on your PC. No docker, no remote server
