### ISSUE TITLE
Question about competition map

### ISSUE THREAD

**Issue by Ha-JH** [jhwangbo/ME491_2022_project#10]
How will the competition map be provided?
Will it be given as a random seed?
Or will it be given verbally (and we would have to implement it)?
Or will you give us the code (obstacleReset)?

Just to make sure, the competition map will be a sample of current environment distribution, correct?

Also, when submit the code, do we have to include weights used for competition?

**Comment by SeungHunJeon** [comment]
How will the competition map be provided?
Will it be given as a random seed?
Or will it be given verbally (and we would have to implement it)?
Or will you give us the code (obstacleReset)?

Just to make sure, the competition map will be a sample of current environment distribution, correct?

>  Not concretely defined yet, but the map would follows the current distribution. 

Also, when submit the code, do we have to include weights used for competition?

> Yes sure
