### ISSUE TITLE
Question on project rule (what is considered as success?)

### ISSUE THREAD

**Issue by Ha-JH** [jhwangbo/ME491_2022_project#11]
As stated in PROJECT_RULE.md and isSuccessState, it seems like it is considered as "success" as long as aliengo's base x,y coordinates are within goal-position's radius and aliengo's z coordinate is irrelevant. 
I am assuming that for the competition, aliengo can jump over the goal region and still be considered as success, correct?
Also, since there is no statement/rule about aliengo getting on the ground, does that mean even if aliengo lands on the ground and runs to the goal-position x,y on the ground, it will be considered as "successful"?

**Comment by SeungHunJeon** [comment]
On the ground is not allowed, the robot must be on or over the flat plate.

It depends on your reward engineering
