### ISSUE TITLE
DLL loading failure while compiling runner.py

### ISSUE THREAD

**Issue by obj153** [jhwangbo/ME491_2022_project#13]
OS: Windows 10
Compiler: Anaconda
Python Version: 3.9.7

When I used Anaconda prompt to compile the runner.py, following errors are occurs.

Traceback (most recent call last):
  File "D:\Documents\KAIST\Graduate\Master\2022\Lecture\ME491\raisim\raisimLib\raisimGymTorch\raisimGymTorch\env\envs\rsg_anymal\runner.py", line 4, in <module>
    from raisimGymTorch.env.bin.rsg_anymal import NormalSampler
ImportError: DLL load failed while importing rsg_anymal: 지정된 모듈을 찾을 수 없습니다.

I already adds 
D:\Documents\KAIST\Graduate\Master\2022\Lecture\ME491\raisim\raisimLib\raisim\win32\bin
where the raisim compiled at PATH

**Comment by SeungHunJeon** [comment]
Check this site [raisim install](https://raisim.com/sections/Installation.html)

I'm not familiar at window, but i think the path seems wrong 'raisim\win32\bin' -> 'raisim\win32'

**Comment by obj153** [comment]
I changed PATH by
'raisim\win32\bin' -> 'raisim\win32'
but do not make any changes and same error occurs.

**Comment by SeungHunJeon** [comment]
Did you build the raisimGymTorch?

python setup.py develop

check this [raisimGymTorch](https://raisim.com/sections/RaisimGymTorch.html)

**Comment by jhwangbo** [comment]
'raisim\win32\bin' is the correct path. Are you using 64 bit python?

**Comment by obj153** [comment]
Yes. I'm using 64 bit python, and I build the raisimGymTorch.

**Comment by obj153** [comment]
I solved the problem by running Annaconda Powershell Prompt.
