### ISSUE TITLE
RaisimUnity version mismatch

### ISSUE THREAD

**Issue by Hjjkim** [jhwangbo/ME491_2022_project#15]
First of all, thanks for preparing for this great competition to TA and professor.

For visualization of pannel showing world time, I just downloaded zip file, extracted, and executed the latest version of RaisimUnity ( 'linux update' 3 weeks ago), and ran the latest version of runner.py code,

and when I clicked the connect button in the RaisimUnity, The error message occurs as below.

[2022:12:07:21:55:17 RaisimServer.hpp:999] Version mismatch. Make sure you have the correct visualizer version

because I installed and compiled the raisim about 3 weeks ago, there would be a version mismatch I think.

I tried to modify the version of RaisimServer.hpp file from 10010 to 10011 as instructed in the below link. 
https://github.com/raisimTech/raisimLib/commit/4a9c87ac4c51820af8aafe45d2bf39ea5625bd85
(I found this modification by clicking the 'linux update' in the raisimUnity folder in github homepage)
I'm not sure this is the right approach, I just thought the (old) server version would change to fit the (new) raisimUnity version.

but still got the same error.

So my question is,
How can I change the Unity version to fit the raisim version? Or how can I do the opposite? 
Should I install and compile the latest version of raisim one more time? 
More detailed instructions for how to pull / reflect the new version of RaisimUnity or Any recommendation would be grateful!

thanks in advance! :)

**Comment by SeungHunJeon** [comment]
When you build through Cmake, there is a process finding raisim package. If the linked raisim library path doesn't the latest version, that error would be occurred. Thus, i recommend you to check the raisim library path through run **python setup.py develop**

If the raisim path : /usr/local/lib, you have to link the target path into manual library path (e.g. $LOCAL_INSTALL ~~ /lib).

note) You must remove the CmakeCache file before execute **python setup.py develop**

**Comment by Hjjkim** [comment]
Thank you for your recommend! I fixed it :)
