### ISSUE TITLE
How to terminate when the robot falls

### ISSUE THREAD

**Issue by KyeongminNam** [jhwangbo/ME491_2022_project#16]
I want to terminate when the robot falls out of the box. So I added
`    if (gc_[2]<1.0){
        return true;
    }`
in the function 
`  bool isTerminalState(float& terminalReward) final {
`
in Environment.hpp, but this doesn't work. And even if I replaced this whole function with return true or return false, it didn't end. 
How should I implement this? Thank you.

**Comment by jhwangbo** [comment]
It shouldn't end. It should reset.
