### ISSUE TITLE
tester.py path issue

### ISSUE THREAD

**Issue by Ha-JH** [jhwangbo/ME491_2022_project#2]
path error when running 
$python raisimGymME491/env/envs/aliengo_jump/tester.py
Error output:
hajh@hydra:~/Workspace/raisim_ws/ME491_2022_project/raisimGymME491/env/envs/aliengo_jump$ python tester.py 
[2022:11:17:21:12:54 ArticulatedSystem.cpp:374] /home/hajh/Workspace/raisim_ws/rsc/env/envs/aliengo_jump/rsc/aliengo/aliengo.urdf does not exist

I was able to fix this by tweaking with paths in tester.py, but I thought that some others might face similar issue

I don't think specs are relevant but fyi:
Graphic card: nvidia RTX A6000
OS: Linux-x86_64 (Ubuntu 22.04)
Nvidia driver version: 515.76

**Comment by SeungHunJeon** [comment]
I checked it, thanks for your comment!
