### ISSUE TITLE
CMake cannot find "Eigen3"

### ISSUE THREAD

**Issue by obj153** [jhwangbo/ME491_2022_project#3]
OS: Windows 10
Compiler: Anaconda
Python Version: 3.9.7

Even though the raisim installation folder is set by CMAKE_PREFIX_PATH, CMAKE cannot find the Eign3 library, so the installation does not proceed. I am getting the following error, is there any solution?

CMake Error at CMakeLists.txt:28 (find_package):
  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by jhwangbo** [comment]
I pushed a fix. can you pull and try again?

**Comment by obj153** [comment]
After applying the fix you posted, the error code changed to:
CMake Error at CMakeLists.txt:71 (find_package):
  Could not find a package configuration file provided by "raisim" with any
  of the following names:

    raisimConfig.cmake
    raisim-config.cmake

  Add the installation prefix of "raisim" to CMAKE_PREFIX_PATH or set
  "raisim_DIR" to a directory containing one of the above files.  If "raisim"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by jhwangbo** [comment]
if you are using windows, pull raisim again. Then pass in the "raisimLib/raisim/win32" path to CMAKE_PREFIX_PATH. I'll talk about it in class as well
