### ISSUE TITLE
episode termination after success?

### ISSUE THREAD

**Issue by Ha-JH** [jhwangbo/ME491_2022_project#8]
![2022-11-25-16-22-07policy_6900 (1)](https://user-images.githubusercontent.com/20591452/203924735-86725615-5f16-4024-a3ed-a18216280abf.gif)

Its seems like episode does not terminate even though aliengo reaches the goal. The simulator does give out True for isSuccessState(). 
Is there a way to terminate the episode once the goal has been reached?

Also, it seems like episode does not terminate when aliengo touches the ground. Is there a way to terminate episode when this happens?

**Comment by SeungHunJeon** [comment]
To answer your question, I intentionally left the part about setting the terminal condition. isSucessState() function simply checks whether the robot reached the goal or not, not to determine the terminal. **You can resolve this issue by adding the Success condition to the isTerminalState() function.**

This is a simple example that how to deal with the terminal condition, I believe that you can solve the latter one as well:)

I will upload the revised version, please check.

Anyway, **did you pull the revised version? or did you modify the difficulty of the environment?**  
the video's environment seems very easy. Please check the current git state and check the latest one.

**Comment by Ha-JH** [comment]
Oh yes, I intentionally modified difficulty of the environment to test curriculum learning. 
Thanks for your response!

**Comment by Ha-JH** [comment]
Oh yes, I intentionally modified difficulty of the environment to test curriculum learning. 
Thanks for your response!
